# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 165c2f80941323cd80319bc65118c0c502e9e49660c32d879bdba3b283725932d2fcc6e0536905139240c44c5bd113fea3ab294a9f1a9a3d732ce1242b77048b

test:
  secret_key_base: 46a7101b2eccb1f50ccde89b54341c9009b825e7d833d0bd1eeab0216fe55b8f36d4805315e4930c945baacbbd57ddb3ab0e0b4cc08812465d08b9ed3c3c1686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
